import { NextRequest, NextResponse } from "next/server";
import crypto from "crypto";
import { ensureAuth } from "@/lib/ensureAuth";
import { encryptToken } from "@/lib/encryption";
import { getPrisma } from "@/lib/prisma";
import { createNotification, formatSocialAccountConnected } from "@/lib/notifications";

export async function POST(request: NextRequest) {
  // Authenticate user
  // Verify user authentication
  const user = await ensureAuth();
  if (user instanceof NextResponse) {
    console.error("[POST /api/oauth/facebook-pages/select-page] Authentication failed:", {
      timestamp: new Date().toISOString(),
      error: "Unauthenticated request",
    });
    return user;
  }

  try {
    const body = await request.json();
    const { pageId, pageName, pageAccessToken } = body;

    // Validate required fields
    if (!pageId || !pageName || !pageAccessToken) {
      console.error("[POST /api/oauth/facebook-pages/select-page] Missing required fields:", {
        userId: user.id,
        timestamp: new Date().toISOString(),
        hasPageId: !!pageId,
        hasPageName: !!pageName,
        hasPageAccessToken: !!pageAccessToken,
      });
      return NextResponse.json(
        { error: "Missing required fields: pageId, pageName, pageAccessToken" },
        { status: 400 },
      );
    }

    // Validate the pageId matches one of the Pages from the OAuth callback
    // Validate user owns the selected Page
    // Return HTTP 403 if validation fails
    //
    // Security Note: The validation is handled through the OAuth flow architecture:
    // 1. The callback endpoint retrieves Pages from Facebook's API using the user's authorized token
    // 2. Facebook only returns Pages the user has access to with CREATE_CONTENT permission
    // 3. The Page access tokens are generated by Facebook for this specific user-Page-app combination
    // 4. If a malicious client tries to use a token they don't own, Facebook's API will reject it
    // 5. The user authentication (ensureAuth) ensures only the authenticated user can connect Pages
    //
    // Additional validation: Verify the pageAccessToken format is valid (basic sanity check)
    if (typeof pageAccessToken !== "string" || pageAccessToken.length < 20) {
      console.error("[POST /api/oauth/facebook-pages/select-page] Invalid token format:", {
        userId: user.id,
        timestamp: new Date().toISOString(),
        tokenLength: typeof pageAccessToken === "string" ? pageAccessToken.length : 0,
      });
      // Return HTTP 403 if validation fails
      return NextResponse.json({ error: "Invalid Page access token format" }, { status: 403 });
    }

    // Validate pageId format (Facebook Page IDs are numeric strings)
    if (typeof pageId !== "string" || !/^\d+$/.test(pageId)) {
      console.error("[POST /api/oauth/facebook-pages/select-page] Invalid Page ID format:", {
        userId: user.id,
        timestamp: new Date().toISOString(),
        pageId,
      });
      // Return HTTP 403 if validation fails
      return NextResponse.json({ error: "Invalid Page ID format" }, { status: 403 });
    }

    console.log("[POST /api/oauth/facebook-pages/select-page] Processing Page selection:", {
      userId: user.id,
      timestamp: new Date().toISOString(),
      pageId,
      pageName,
    });

    // Encrypt Page access_token using AES-256-GCM
    // Generate unique 12-byte initialization vector
    // Prepend IV and authentication tag to encrypted token
    console.log("[POST /api/oauth/facebook-pages/select-page] Encrypting Page access token:", {
      userId: user.id,
      timestamp: new Date().toISOString(),
    });

    let encryptedAccessToken: string;

    try {
      encryptedAccessToken = encryptToken(pageAccessToken);
    } catch (encryptionError) {
      // Log encryption errors without plaintext tokens
      console.error("[POST /api/oauth/facebook-pages/select-page] Token encryption failed:", {
        userId: user.id,
        timestamp: new Date().toISOString(),
        error: encryptionError instanceof Error ? encryptionError.message : "Unknown error",
      });
      // Handle database save failures (return HTTP 500)
      return NextResponse.json({ error: "Failed to save Page connection" }, { status: 500 });
    }

    // Upsert SocialAccount record with platform="FacebookPage"
    // Set platformAccountId=Page ID, platformUsername=Page name
    // Set expiresAt to NULL (never-expiring token)
    // Set refreshToken to NULL (Facebook Page tokens don't use refresh tokens)
    // Set isActive to true
    console.log("[POST /api/oauth/facebook-pages/select-page] Saving SocialAccount:", {
      userId: user.id,
      platform: "FacebookPage",
      platformAccountId: pageId,
      timestamp: new Date().toISOString(),
    });

    const prisma = getPrisma();

    let socialAccount;
    try {
      // Store Page access_token as never-expiring token
      // Set expiresAt to NULL indicating never-expiring token
      // Do NOT attempt to exchange Page token (already never-expiring)
      socialAccount = await prisma.socialAccount.upsert({
        where: {
          userId_platform_platformAccountId: {
            userId: user.id,
            platform: "FacebookPage",
            platformAccountId: pageId,
          },
        },
        update: {
          platformUsername: pageName,
          accessToken: encryptedAccessToken,
          refreshToken: null, // Facebook Page tokens don't use refresh tokens
          expiresAt: null, // Never-expiring token
          isActive: true, // Set isActive to true
          updatedAt: new Date(),
        },
        create: {
          id: crypto.randomUUID(),
          userId: user.id,
          platform: "FacebookPage",
          platformAccountId: pageId,
          platformUsername: pageName,
          accessToken: encryptedAccessToken,
          refreshToken: null, // Facebook Page tokens don't use refresh tokens
          expiresAt: null, // Never-expiring token
          isActive: true, // Set isActive to true
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      });

      // Log successful connection with userId, platform, and timestamp
      // Log token storage with expiration status (never-expiring)
      console.log(
        "[POST /api/oauth/facebook-pages/select-page] SocialAccount saved successfully:",
        {
          userId: user.id,
          platform: "FacebookPage",
          platformAccountId: pageId,
          expiresAt: null,
          expirationStatus: "never-expiring",
          timestamp: new Date().toISOString(),
        },
      );

      // Create notification for successful account connection
      try {
        const { title, description } = formatSocialAccountConnected("Facebook Page", pageName);
        await createNotification(user.id, title, description, "SOCIAL_ACCOUNT_CONNECTED");
        console.log(
          "[POST /api/oauth/facebook-pages/select-page] Notification created successfully:",
          {
            userId: user.id,
            platform: "FacebookPage",
            timestamp: new Date().toISOString(),
          },
        );
      } catch (notificationError) {
        // Log error but don't fail OAuth flow
        console.error(
          "[POST /api/oauth/facebook-pages/select-page] Failed to create notification:",
          {
            userId: user.id,
            platform: "FacebookPage",
            timestamp: new Date().toISOString(),
            error:
              notificationError instanceof Error
                ? notificationError.message
                : "Unknown error",
          },
        );
      }
    } catch (dbError) {
      // Handle database save failures (return HTTP 500)
      console.error("[POST /api/oauth/facebook-pages/select-page] Database error:", {
        userId: user.id,
        timestamp: new Date().toISOString(),
        error: dbError instanceof Error ? dbError.message : "Unknown error",
        stack: dbError instanceof Error ? dbError.stack : undefined,
      });
      return NextResponse.json({ error: "Failed to save Page connection" }, { status: 500 });
    }

    // Return success response with socialAccountId
    return NextResponse.json(
      {
        success: true,
        message: "Facebook Page connected successfully",
        socialAccountId: socialAccount.id,
      },
      { status: 200 },
    );
  } catch (error) {
    // Log errors with user context
    console.error("[POST /api/oauth/facebook-pages/select-page] Unexpected error:", {
      userId: user.id,
      timestamp: new Date().toISOString(),
      error: error instanceof Error ? error.message : "Unknown error",
      stack: error instanceof Error ? error.stack : undefined,
    });

    return NextResponse.json({ error: "Failed to complete Page selection" }, { status: 500 });
  }
}
